package com.emc.moodmingle.navigation

sealed class Routes(val route: String) {
    object Login : Routes("login")
    object Register : Routes("register")
    object Home : Routes("home")
    object Create : Routes("create")
    object CreatePost : Routes("create_post")
    object CreateDailyMood : Routes("create_daily_mood")
    object Insights : Routes("insights")
    object Search : Routes("search")
    object SearchResult : Routes("search_result")
    object Personal : Routes("personal")
    object Password : Routes("password")
    object VerifyPassword : Routes("verify_password")
    object ChangePassword : Routes("change_password")
    object ForgotPassword : Routes("forgot_password")
    object VerifyCode : Routes("verify_code")
    object ResetPassword : Routes("reset_password")
    object Favorites : Routes("favorites")
    object Save : Routes("saved")
    object Privacy : Routes("privacy")
    object Security : Routes("security")
    object Encryption : Routes("encryption")
    object Decryption : Routes("decryption")
    object Chat : Routes("chat/{senderId}/{receiverId}")
    object Conversation : Routes("conversation")
    object Remix : Routes("remix/{entityId}/{type}")
    object Music : Routes("music")
    object DailyMood : Routes("daily_mood")

    object BottomHome : Routes("home_tab")
    object BottomNotification : Routes("notification_tab")
    object BottomVideo : Routes("video_tab")
    object BottomProfile : Routes("profile_tab")
    object BottomSettings : Routes("settings_tab")
    object BottomMusic : Routes("music_tab")
}